### ISSUE TITLE
[FEAT] 주제, 선택지 조회 기능 구현

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#14]
## Description 💭
```
[GET] http://localhost:8080/api/balances/rooms/{roomId}/question
```

## TODO ✅
- [x] #19
- [x] #28

### Reference 🔎
[ERD](https://www.erdcloud.com/d/8WoFz6FREzz952yTM)
[API 문서](https://www.notion.so/ghenmaru/API-9c461698fded43e2a0441cf93de3e79b?pvs=4#043a061e6e7f412480a8c24baad49c0f)

**Comment by leegwichan** [comment]
작업 완료하여 Issue 닫겠습니다~
