### ISSUE TITLE
[FEAT] 투표 결과 저장 기능 구현

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#15]
## TODO ✅
- [ ] 투표 결과 저장 기능을 구현한다.

### Reference 🔎
[API 문서](https://www.notion.so/ghenmaru/API-9c461698fded43e2a0441cf93de3e79b?pvs=4#a0eaba632e284d7cbef3ad2058ff618c)

**Comment by leegwichan** [comment]
API 문서

`POST` http://localhost:8080/api/balances/rooms/{roomId}/contents/{contentId}/votes

### Request

**[Header]**

**[Body]**

```json
{
	"memberId": 1,
	"optionId" : 1
}
```

### Response

**[Header]**

<aside>
➡️ HTTP/1.1 **201 CREATED**
Content-Type: application/json
Location: ??

</aside>

**[Body]**

```json
{
	"optionId" : 1
}
```
