### ISSUE TITLE
[FEAT] 방에서 나가기 API

### ISSUE THREAD

**Issue by leegwichan** [woowacourse-teams/2024-ddangkong#209]
## Description 💭

- 유저가 중간에 나갔을 경우 요청할 '방에서 나가기 API' 구현

## TODO ✅

- 모든 경우
    - 방에서 해당 멤버 삭제 (Soft Delete)
    - Cookie max-age = 0으로 설정
- 방장일 경우
    -  다른 멤버에게 방장 양도
- 방에 모든 멤버가 나갔을 때
    - 투표 기록을 전체 투표 기록으로 옮김
    - 룸 컨텐츠 삭제(Hard Delete)
    - 방과 멤버들을 삭제 (Hard Delete)
- 배치 처리
    - 20분 주기로 2시간 동안 변화가 없는 방은 제거

### Reference 🔎
https://www.notion.so/ghenmaru/API-v3-5ab9dcc744144fd38fdd2aaaf52117ea?p=5acd2f89db5343638b109eed7d32f3ba&pm=s

**Comment by PgmJun** [comment]
쿠키 관련 PR 머지되면 나갈 때 Cookie max-age 0으로 설정하는 작업도 부탁해요~!
